#! /bin/bash

_wpactl_bash_autocomplete() {
  local CMDS_REQUIRE_IFACE='status st up down dn scan sc scan-results sr scr reconnect rc disconnect dc reassociate ra reattach rat signal_poll flush_bss'
  if [[ "${COMP_WORDS[0]}" != source ]]; then
    local cur opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ "$cur" == "-"* ]]; then
      opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} ${cur} --generate-bash-completion )
    elif __contains_word "${COMP_WORDS[1]}" $CMDS_REQUIRE_IFACE ; then
	    opts=$( __get_links )
    elif test "${COMP_WORDS[1]}" = networks && __contains_word "${COMP_WORDS[2]}" list ls disable enable remove select add ; then
	    opts=$( __get_links )
    elif test "${COMP_WORDS[1]}" = blob && __contains_word "${COMP_WORDS[2]}" list remove add get ; then
	    opts=$( __get_links )
    else
      opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
    fi
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
  fi
}

type __get_links >& /dev/null || source /usr/share/bash-completion/completions/networkctl
complete -o bashdefault -o default -F _wpactl_bash_autocomplete wpactl
